# Welcome to Jekyll!
#

# Site settings
title: Pirátská strana | MORAVSKOSLEZSKÝ KRAJ
email: pavel.korizek@pirati.cz
description: > # this means to ignore newlines until "baseurl:"
  Web krajského sdružení České pirátské strany v Moravskoslezském kraji.
keywords: piráti, česká pirátská strana, svoboda, demokracie, moravskoslezký kraj, slezko, MSK
url: "https://moravskoslezsky.pirati.cz" # the base hostname & protocol for your site



administrator:
  email: pavel.korizek@pirati.cz # mail kam pujdou chybove vystupy

organization:
  name: Pirátská strana | MORAVSKOSLEZSKÝ KRAJ
  shortName: Piráti MSK
  contactUid: pavel.korizek
  email: pavel.korizek@pirati.cz
  phone: +420 777 237 635
  address: |
    Řehořova 943/19, 
    130 00 Praha 3
  residenceImg:
  mapLink: https://mapy.cz/zakladni?vlastni-body&x=14.4418976&y=50.0863156&z=18&ut=PiCe&uc=9h2F.xXwtn&ud=ulice%20%C5%98eho%C5%99ova%20943%2F19%2C%20Praha%2C%20130%2000%2C%20okres%20Hlavn%C3%AD%20m%C4%9Bsto%20Praha
  redmineLink: https://redmine.pirati.cz/projects

video:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
  title: Krajský kalendář
  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=550&amp;wkst=2&amp;bgcolor=%23ffffff&amp;src=i7ipksvi9b852grgjic8mnhua0%40group.calendar.google.com&ctz=Europe%2FPrague

calendar:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
  title: Krajský kalendář
  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=550&amp;wkst=2&amp;bgcolor=%23ffffff&amp;src=i7ipksvi9b852grgjic8mnhua0%40group.calendar.google.com&ctz=Europe%2FPrague

facebook:
  loadSDK: true
  #vyplně adresu vaší stranky, funguje pouze na stránky nikoliv skupiny
  profilePage: https://www.facebook.com/cpsmsk/ 
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

gplus:
  profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/moravskoslezky.pirati.cz/
  branch: master


###################technické

github_username:  pirati-web

sass:
  style: compressed
  sass_dir: _sass

theme: jekyll-theme-pirati

markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /volby/:path/
  teams:
    output: true
    permalink: /pripoj-se/:title/
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar: foto 
          #- foto
          #- personContact
          #- people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar: "volby"
      #- garant
      #   - program
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar: "team-summary, teams-toc"

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-5.0.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - assets/img/posts
    - _sass
